{% set name = "tidy-html5" %}
{% set version = "5.9.14" %}
{% set sha = "83cc9d9cdfa59bfe400dc745dea14eb1e1be4ca088facfb911eac8b78e75f2b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/htacg/{{ name }}/archive/{{ version }}-next.tar.gz
  sha256: {{ sha }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - tidy -h

about:
  home: http://www.html-tidy.org/
  license: MIT
  license_family: MIT
  license_file: README/LICENSE.txt
  summary: The granddaddy of HTML tools, with support for modern standards.
  description: |
    Tidy tidies HTML and XML. It can tidy your documents by itself, and
    developers can easily integrate its features into even more powerful tools.
  doc_url: http://www.html-tidy.org/
  dev_url: https://github.com/htacg/tidy-html5

extra:
  recipe-maintainers:
    - asford
    - thewchan
