{% set name = "tidy-html5" %}
{% set version = "5.8.0" %}
{% set sha = "59c86d5b2e452f63c5cdb29c866a12a4c55b1741d7025cf2f3ce0cde99b0660e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/htacg/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - tidy -h

about:
  home: http://www.html-tidy.org/
  license: MIT
  license_family: MIT
  license_file: README/LICENSE.txt
  summary: The granddaddy of HTML tools, with support for modern standards.
  description: |
    Tidy tidies HTML and XML. It can tidy your documents by itself, and
    developers can easily integrate its features into even more powerful tools.
  doc_url: http://www.html-tidy.org/
  dev_url: https://github.com/htacg/tidy-html5

extra:
  recipe-maintainers:
    - asford
    - thewchan
